### ISSUE TITLE
global 'document' variable is missing from the global variable list.

### ISSUE THREAD

**Issue by fakalit** [shendepu/nashorn-polyfill#1]
global variables defined by the polyfill like "global, window, self, console, process" don't include document? is this by design?

**Comment by shendepu** [comment]
Yes, it is by design. 

This polyfill is not targeting to simulate web browser environment, but providing sufficient support of environment to do server-side rendering for React (vuejs, angular 2 etc) that does not rely on DOM api when rendering on server-sider.

Meanwhile there are some stuff does not need to run on server side, so their support is limited. e.g. FormData, usually FormData is used after user input, but there is no user input when rendering on server. 

In React application, `document` still can be used in event handler, but not in render or component lifecycle methods.

**Comment by fakalit** [comment]
I agree that most of the time that is the case.  though for us, one of the polyfills we used in our server rendered react project, (https://github.com/chrisdickinson/raf) references document object. we try to apply the polyfills before all renders and lifecycle methods, which causes a problem during initial render. 

finding out a way to omit that polyfill from the server build fixes our problem, but I figured you might want to know this use-case to make a more informed decision about the design.

**Comment by shendepu** [comment]
Thanks for sharing. 

I think if doing server-side rendering, DOM related API should be ensured that they are not called in render. Otherwise the library has to be thrown away if no walkaround. The degrade approach is to check if document exists before use it.

The reason is simple: if code throws exception because of `document` is undefined, then adding a fake `var document = {}` does not help since the code will continue to call something like `document.getElementById()`, but that function is undefined. It can go on and on, then it eventually require a full DOM API polyfill which is hard.
