### ISSUE TITLE
Document how to add this polyfill to a nashorn instance

### ISSUE THREAD

**Issue by iszlai** [shendepu/nashorn-polyfill#2]
Maybe it’s just hard to find but i didn’t see an example of how to actually load this polyfill only it’s dependencies. It would really help newcommers to get started even if it’s just a three line snippet

**Comment by shendepu** [comment]
This polyfill only should be load on server, not brower, since its purpose is to polyfill JVM `Nashorn` engine. 

There is a moqui add-on [Moqui React SSR](https://github.com/shendepu/moqui-react-ssr). You may check out the detail of `React` and `ReactRender` class to see how to initialize `Nashorn` with scripts. There are some optimization techniques of caching scripts and reusing nashorn instance might complex the code. But it is still fair simple.
